default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: yuusuke
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: tabi_note_development

test:
  <<: *default
  database: tabi_note_test

production:
  <<: *default
  database: tabi_note_production
